/**
* @author        Rahul Yadav
* @date          29-June-2024
* @description   This class is used to send request paremeter with below varialbes.
* Modification Log:
  --------------------------------------------------------------------------------------------
  Developer             Date            Description
  --------------------------------------------------------------------------------------------
  Rahul Yadav           29-June-2024    Initial Version
*/
public without sharing class AUSF_INT_ElectricityBillRequestWrapper {
        public String consent;
        public String service_provider;
        public String consumer_id;
        public String ReqId;
        public String Channel;
}