/* @author        Pradeep Sharma
 * @date          05-July-2024
 * @description   Wrapper to store Request body
 * Modification Log:
--------------------------------------------------------------------------------------------
  Developer             Date            Description
  --------------------------------------------------------------------------------------------
  Pradeep Sharma        05-July-2024    Initial Version
   */
public class AUSF_DocumentCompressRequestWrappper {
  public AUSF_DocumentCompressRequestWrappper(){}
  public String RequestId;
  public String OriginatingChannel;
  public String filename;
  public String base64string;
}