/**
 * @author              : Amit Mishra
 * @date                : 12-Aug-2024
 * @description         : BRE UNDERWRITING API Test class for AUSF_INT_BRE_UNDERWRITING_Controller, AUSF_INT_BRE_UNDERWRITING_Handler, AUSF_INT_BRE_UNDERWRITING_Request, AUSF_INT_BRE_UNDERWRITING_Response
 * History              :
 * ===========================================================================================================
 * <Date> 		<Authors Name> 		<Brief Description of Change>
 * ===========================================================================================================
 * 12-Aug-2024 	Amit Mishra 		Initial Version
**/
@isTest
public without sharing class AUSF_INT_BRE_UNDERWRITING_Test {
    
}