/**
 * @author              : Amit Mishra
 * @date                : 25-June-2024
 * @description         : Request wrapper for NSDL PAN API callout
 * Test Class           : AUSF_NsdlPanTest
 * History              :
 * ====================================================================
 * <Date> 		<Authors Name> 		<Brief Description of Change>
 * ====================================================================
 * 25-June-2024 	Amit Mishra 		Initial Version
**/
public without sharing class AUSF_NsdlPanRequestWrapper {
    public String Pan;
    public String DateOfBirth;
    public String OriginatingChannel;
    public String RequestId;
    public String Name;
}