/**
 * @author       Pradeep Sharma
 * Class :		 AUSF_ICSIRequestWrapper
 * @date         05-Aug-2024
 * @description: Integration Request wrapper for ICSI API
 * Modification Log:
--------------------------------------------------------------------------------------------
    Developer             Date            Description
--------------------------------------------------------------------------------------------
    Pradeep Sharma        05-Aug-2024    Initial Version
*/
public class AUSF_ICSIRequestWrapper{
    public AUSF_ICSIRequestWrapper(){}
    public String Consent;
    public String MembershipNo;
    public String OriginatingChannel;
    public String CpNo;
    public String RequestId;
}