/**
 * @author       Ankit Bansal
 * Class :		 AUSF_ICWAI_APIRequestWrapper
 * @date         06-Aug-2024
 * @description: Request wrapper for ICWAI API
 * Modification Log:
--------------------------------------------------------------------------------------------
    Developer             Date            Description
--------------------------------------------------------------------------------------------
    Ankit Bansal          06-Aug-2024     Initial Version
*/
public class AUSF_ICWAI_APIRequestWrapper {
    public AUSF_ICWAI_APIRequestWrapper(){}
    public String Consent;
    public String MembershipNo;
    public String OriginatingChannel;
    public String ContactDetails;
    public String RequestId;
}