/**
* @author        Tejendra
* @date          29-July-2024
* @description   Wrapper for Fetching GST using PAN request payload
* Modification Log:
--------------------------------------------------------------------------------------------
Developer             Date            Description
--------------------------------------------------------------------------------------------
Tejendra            29-July-2024     Initial Version - APL-150
*/
public without sharing class AUSF_GstPanRequestWrapper {
    public AUSF_GstPanRequestWrapper() {

    }
    public String requestid;
    public String channel;
    public String consent;
    public String pan;
}