/**
* @author        Rahul Yadav.
* @date          09-July-2024
* @description   This class will be store request info.
* Test Class     AUSF_INT_PreApprovedTest
--------------------------------------------------------------------------------------------
Developer             Date            Description
--------------------------------------------------------------------------------------------
Rahul Yadav.          09-July-2024    Initial Version
*/
public without sharing class AUSF_INT_PreApprovedRequestWrapper {
    public string RequestId;
    public string OriginatingChannel;
    public string OfferActive;
    public string ItemType;
    public string ItemId;
}