/**
 * @author       Pradeep Sharma
 * Class :		 AUSF_ICAI_APIRequestWrapper
 * @date         05-Aug-2024
 * @description: Integration Request Wrapper for ICAI API
 * Modification Log:
--------------------------------------------------------------------------------------------
    Developer             Date            Description
--------------------------------------------------------------------------------------------
    Pradeep Sharma        05-Aug-2024    Initial Version
*/
public class AUSF_ICAI_APIRequestWrapper{
    
    public AUSF_ICAI_APIRequestWrapper(){}
    public String Consent;
    public String MembershipNo;
    public String OriginatingChannel;
    public String ContactDetails;
    public String RequestId;
}