/**
* @author        Pradeep Sharma
* @date          28-June-2024
* @description   Wrapper to store Request body
* Modification Log:
  --------------------------------------------------------------------------------------------
  Developer             Date            Description
  --------------------------------------------------------------------------------------------
  Pradeep Sharma        28-June-2024    Initial Version
*/
public class AUSF_CustomerDedupeRequestWrapper {
    public AUSF_CustomerDedupeRequestWrapper(){}
    public String AadhaarNumber;
    public String MobileNumber;
    public String LandLineNumber;
    public String CustomerId;
    public String VoterID;
    public String DrivingLicense;
    public String FullName;
    public String ReferenceNumber;
    public String PanNumber;
    public String Channel;
    public String PassportNumber;
    public String RequestId;
    public String TransactionBranch;
    public String DateOfBirth;
    
}