/**
 * @author              : Amit Mishra
 * @date                : 08-Aug-2024
 * @description         : BRE UNDERWRITING API Response Wrapper
 * Test Class           : 
 * History              :
 * ===========================================================================================================
 * <Date> 		<Authors Name> 		<Brief Description of Change>
 * ===========================================================================================================
 * 20-June-2024 	Amit Mishra 		Initial Version
**/

/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-12-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class AUSF_INT_BRE_UNDERWRITING_Response {
    public AUSF_INT_BRE_UNDERWRITING_Response() {

    }
}