/**
 * @author        Enuganti Ram
 * @date          07-July-2024
 * @description   Fetch Shop Establishment details wrapper class
 * Modification Log:
--------------------------------------------------------------------------------------------
    Developer             Date            Description
    --------------------------------------------------------------------------------------------
    Enuganti Ram              07-July-2024    Initial Version - APL-204
*/

public class AUSF_ShopEstablishmentRequestWrapper {
    public String requestid;
    public String channel;
    public String regNo;
    public boolean pdfRequired;
    public String areaCode; 
    public String consent;

    public AUSF_ShopEstablishmentRequestWrapper(){}
}