/**
 * @author              : Amit Mishra
 * @date                : 03-Aug-2024
 * @description         : FSSAI API Request Wrapper Class
 * Test Class           : AUSF_INT_FSSAI_Test
 * History              :
 * ===========================================================================================================
 * <Date> 		<Authors Name> 		<Brief Description of Change>
 * ===========================================================================================================
 * 03-Aug-2024 	Amit Mishra 		Initial Version
**/
public without sharing class AUSF_INT_FSSAI_RequestWrapper {
    public AUSF_INT_FSSAI_RequestWrapper() {}
    public String RequestId;
    public String OriginatingChannel;
    public String Consent;
    public String RegNo;
}